server:
  port: 8999

eureka:
  instance:
  hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: limit-service
          uri: lb://limit-service
          predicates:
            - Path=/limitService/**
        - id: currency-exchange
          uri: lb://currency-exchange
          predicates:
            - Path=/currency/**